<div class="product-inquiry">
    <?php //print_r($block->getProductDetails()) ?>
    <form action="<?= $block->getFormAction() ?>" method="post" id="product-inquiry-form" data-mage-init='{"validation": {}}'>
        <input type="hidden" name="product_id" value="<?= $block->getProductDetails()['id'] ?>">
        <input type="hidden" name="sku" value="<?= $block->getProductDetails()['sku'] ?>">
        <input type="hidden" name="url" value="<?= $block->getProductDetails()['url'] ?>">
        <input type="hidden" name="status" value="inquiry sent to admin">
        <div class="field customer-name">
            <label for="customer_name" class="label"><span><?= __('Your Name') ?></span></label>
            <div class="control">
                <input type="text" id="customer_name" name="customer_name" class="input-text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field customer-email">
            <label for="customer_email" class="label"><span><?= __('Your Email') ?></span></label>
            <div class="control">
                <input type="email" id="customer_email" name="customer_email" class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field inquiry-subject">
            <label for="inquiry_subject" class="label"><span><?= __('Inquiry Subject') ?></span></label>
            <div class="control">
                <input type="text" id="inquiry_subject" name="inquiry_subject" class="input-text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field inquiry-message">
            <label for="inquiry_message" class="label"><span><?= __('Inquiry Message') ?></span></label>
            <div class="control">
                <textarea id="inquiry_message" name="inquiry_message" class="input-textarea" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" title="<?= __('Submit Inquiry') ?>" class="action submit primary">
                    <span><?= __('Submit Inquiry') ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
